print("First 10 letter in lower case ")
t=head(letters,10)
print(t)
print("last 10 letter in upper")
t=tail(LETTERS,10)
print(t)
print("extract letter between 22nd to 24th letter in upper")
e=tail(letters[22:24])
print(e)